modLoader = "scorge"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/elytra/BTFU/issues"
license = "All Rights Reserved"
showAsResourcePack = false

[[mods]]
modId = "btfu"
version = "2.5.1"
entryClass = "btfubackup.BTFU"
displayName = "BTFU"
displayURL = "https://github.com/elytra/BTFU"
authors = "capitalthree, offbeatwitch"
credits = "sefodopo"
description = """
    Server backup done right
    """
